apiVersion: batch/v1
kind: CronJob
metadata:
  name: djapp-clearsessions-cron
  namespace: edu-festive-ganguly
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: djapp-container
            image: paraigor/djapp:cc80a937c736b60a56c9407102fe4c574969eca6
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: djapp-secret
            command: ["python", "manage.py", "clearsessions"]
          restartPolicy: Never
