apiVersion: v1
kind: Secret
metadata:
  name: djapp-secret
  namespace: edu-festive-ganguly
stringData:
  DEBUG: 'True'
  ALLOWED_HOSTS: '127.0.0.1,localhost,your-domain'
  SECRET_KEY: 'xxxxXxxxXxXXxxXXXXXXxxXXxXX'
  DATABASE_URL: 'postgres://user:pass@host.yandexcloud.net:6432/base?sslmode=require'