apiVersion: v1
kind: Service
metadata:
  name: djapp-service
  namespace: edu-festive-ganguly
spec:
  selector:
    entity: djapp-pod
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31245
      port: 80
      targetPort: 80
