apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: edu-festive-ganguly
  labels:
    entity: nginx-service  
spec:
  selector:
    entity: nginx-pod
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 31245
      port: 80
      targetPort: 80
