apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: edu-festive-ganguly
  labels:
    entity: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.27.4
    ports:
    - containerPort: 80
