apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: edu-festive-ganguly
spec:
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      command:
        - /bin/bash
        - -c
        - apt-get update && apt-get install -y postgresql-client && sleep infinity
      volumeMounts:
        - mountPath: /root/.postgresql
          name: pg-root-cert
          readOnly: true
  volumes:
    - name: pg-root-cert
      secret:
        secretName: pg-root-cert
