apiVersion: batch/v1
kind: CronJob
metadata:
  name: djapp-clearsessions-cron
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: djapp-container
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: djapp-secret
            command: ["python", "manage.py", "clearsessions"]
          restartPolicy: Never
