apiVersion: v1
kind: Secret
metadata:
  name: djapp-secret
stringData:
  DEBUG: 'True'
  ALLOWED_HOSTS: '127.0.0.1,localhost,192.168.49.2,star-burger.test'
  SECRET_KEY: 'xxxXXXXxXxxxXXXxxXXxXXxXxXXXxxxxx'
  DATABASE_URL: 'postgres://user:pass@host:5432/base'