apiVersion: batch/v1
kind: CronJob
metadata:
  name: djapp-clearsessions-cron
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: djapp-container
            image: django_app:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DEBUG
              value: "True"
            - name: ALLOWED_HOSTS
              value: "127.0.0.1,localhost,192.168.49.2,star-burger.test"
            envFrom:
            - secretRef:
                name: djapp-secret
            command: ["python", "manage.py", "clearsessions"]
          restartPolicy: Never
